### ISSUE TITLE
Hangman game Issue

### ISSUE THREAD

**Issue by MidnightSpero** [badgeteam/hackerhotel-2024-firmware-esp32c6#40]
The first letter of the Victorian Hangman game is a capital letter, yet the letter you put in is a lower case so the letter is not accepted.

Way to replicate:

- Start up hangman game
- Put in first letter of the word (This should be known by badge team, sorry peeps no spoilers here :) )
- Notice that the letter is counted as being wrong

Issue replicated

**Comment by Kuristian** [comment]
Fixed! see https://github.com/badgeteam/hackerhotel-2024-firmware-esp32c6/issues/57
